package errr

import (
	"errors"
)

var (
	ErrInternalServerError        = errors.New("internal Server Error")
	ErrConflict                   = errors.New("your data already exist")
	ErrBadParamInput              = errors.New("given Param is not valid")
	ErrEmailWrong                 = errors.New("format email wrong")
	ErrGenerateToken              = errors.New("generate token failed")
	ErrPasswordMatch              = errors.New("password do not match")
	ErrPasswordLessContain        = errors.New("password must be at least 8 characters long")
	ErrPasswordLongContain        = errors.New("password must be less than 128 characters long")
	ErrPasswordUppercaseContain   = errors.New("password must contain at least one uppercase letter")
	ErrPasswordLowercaseContain   = errors.New("password must contain at least one lowercase letter")
	ErrPasswordOneNumberContain   = errors.New("password must contain at least one number")
	ErrPasswordSpecialCharContain = errors.New("password must contain at least one special character")
	ErrRoleNotFound               = errors.New("role not found")
	ErrUserNotFound               = errors.New("user not found")
	ErrCompanyNotFound            = errors.New("company not found")
	ErrDiscountNotFound           = errors.New("discount not found")
	ErrCustomerTicketNotFound     = errors.New("customer ticket not found")
	ErrStockTypeNotFound          = errors.New("stock type not found")
	ErrTicketNotFound             = errors.New("ticket not found")
	ErrProductNotFound            = errors.New("product not found")
	ErrBookingItemNotFound        = errors.New("booking not found")
	ErrInvalidCredential          = errors.New("invalid credential")
	ErrCompanyIsDeleted           = errors.New("company not found, please call in administrator for open your account")
	ErrorDuplicatePhone           = errors.New("phone number is registered")
	ErrorDuplicateProduct         = errors.New("product is registered")
	ErrImageMaxSize               = errors.New("image size max 5 MB")
	ErrImageTypeNotValid          = errors.New("file name not valid, only accept jpg, jpeg, png")
	ErrEmailAlreadyExist          = errors.New("email is registered")
	ErrTncNotFound                = errors.New("term and condition not found")
	ErrPhotoNotFound              = errors.New("photo not found")
	ErrCompanyTypeNotFound        = errors.New("company type not found")
	ErrUserAlreadyExist           = errors.New("user is ready")
	ErrClientNotFound             = errors.New("client not found")
	ErrBedTypeNotFound            = errors.New("bed type not found")
	ErrRoomTypeNotFound           = errors.New("room type not found")
	ErrCategoryFacilityNotFound   = errors.New("category facility not found")
	ErrFacilityNotFound           = errors.New("facility not found")
	ErrProductCategoryNotFound    = errors.New("kategori produk tidak ditemukan")
	ErrClientTypeNotFound         = errors.New("tipe klien tidak ditemukan")
	ErrSegmentNotFound            = errors.New("segmen tidak ditemukan")
	ErrBrandNotFound              = errors.New("brand not found")
	ErrBrandAlreadyExists         = errors.New("this brand name is ready")
	ErrVehicleTypeNotFound        = errors.New("vehicle type not found")
	ErrVehicleTypeAlreadyExists   = errors.New("this vehicle type name is ready")
	ErrVehicleNotFound            = errors.New("vehicle not found")
	ErrVehicleAlreadyExists       = errors.New("this vehicle name is ready")
	ErrAreaNotFound               = errors.New("area not found")
	ErrAreaAlreadyExists          = errors.New("this area name is ready")
	ErrChannelNotFound            = errors.New("channel not found")
	ErrChannelAlreadyExists       = errors.New("this channel name is ready")
)

var (
	ErrHashPassword                     = errors.New("error when hash password")
	ErrVerifyPassword                   = errors.New("error when verify password")
	ErrCreateAccessToken                = errors.New("error when create access token")
	ErrCreateRefreshToken               = errors.New("error when create refresh token")
	ErrGetAccessToken                   = errors.New("error when get access token from cache")
	ErrGetRefreshToken                  = errors.New("error when get refresh token from cache")
	ErrStoreAccessToken                 = errors.New("error when store access token to cache")
	ErrStoreRefreshToken                = errors.New("error when store refresh token to cache")
	ErrDeleteAccessToken                = errors.New("error when delete access token from cache")
	ErrDeleteRefreshToken               = errors.New("error when delete refresh token from cache")
	ErrUnmarshalSessionID               = errors.New("error when unmarshal session id from cache")
	ErrVerifyToken                      = errors.New("error when verify token")
	ErrCreateUserSession                = errors.New("error when create user session")
	ErrUpdateUserSession                = errors.New("error when update user session")
	ErrGetDataAuthorization             = errors.New("error when get data authorizaton grpc")
	ErrChangeUserPassword               = errors.New("error when update user password")
	ErrResetPassword                    = errors.New("error when reset user password")
	ErrGetSessionIDFromCache            = errors.New("error when get session id from cache")
	ErrStoreSessionIDToCache            = errors.New("error when store session id to cache")
	ErrDeleteSessionIDFromCache         = errors.New("error when delete session id from cache")
	ErrStoreLoginRateLimitToCache       = errors.New("error when store login rate limit to cache")
	ErrGetLoginRateLimitFromCache       = errors.New("error when get login rate limit from cache")
	ErrDeleteLoginRateLimitFromCache    = errors.New("error when delete login rate limit from cache")
	ErrLoginThresholdExceeded           = errors.New("error login threshold exceeded")
	ErrGenerateOtp                      = errors.New("error when generate otp")
	ErrStoreOtpToCache                  = errors.New("error when store OTP to cache")
	ErrGetOtpFromCache                  = errors.New("error OTP not found in cache")
	ErrVerifyOtp                        = errors.New("error when verify OTP")
	ErrDeleteOtp                        = errors.New("error when delete OTP")
	ErrUnmarshalXmlBody                 = errors.New("error when unmarshal xml body from response")
	ErrUnmarshalJsonBody                = errors.New("error when unmarshal json body from response")
	ErrForceLogoutStoreSessionIdToCache = errors.New("error when (force logout) store the session id to cache")
	ErrForceLogoutDecodeSessionId       = errors.New("error when (force logout) decode the session id")
	ErrGenerateLink                     = errors.New("error when generate session logout link")
	ErrSendEmail                        = errors.New("error when send email")
)

var (
	ErrInvalidPayloadParameter           = errors.New("invalid payload parameters")
	ErrInvalidKeySize                    = errors.New("invalid key size: must be at least %d character")
	ErrSessionIDNotFound                 = errors.New("session anda sudah habis, Silakan login ulang")
	ErrSessionAppIDNotFound              = errors.New("session aplikasi anda tidak valid, Silakan login ulang")
	ErrExpiredToken                      = errors.New("session anda sudah habis, Silakan login ulang")
	ErrInvalidToken                      = errors.New("session anda tidak valid, Silakan login ulang")
	ErrAuthorizationHeaderInvalid        = errors.New("the authorization header is invalid")
	ErrAuthorizationHeaderInvalidExample = errors.New("%s <token>")
	ErrAuthorizationTypeInvalid          = errors.New("the authorization type is invalid")
	ErrSpecificHeaderRequired            = errors.New("%s header is required")
)

var (
	ErrConnectionToDB       = errors.New("failed to connect to db: %w")
	ErrConvertStrToDateTime = errors.New("kesalahan saat mengonversi string ke datetime. %v")
)

var (
	Err                 = errors.New("error")
	ErrGeneral          = errors.New("error general")
	ErrBadRequest       = errors.New("error bad request")
	ErrDataNotFound     = errors.New("error data not found")
	ErrDataAlreadyExist = errors.New("error data already exist")
	ErrFormatting       = errors.New("error formatting")
	ErrDatabase         = errors.New("error database")
	ErrAsyncKafka       = errors.New("error async kafka")
	ErrTimeout          = errors.New("error timeout")
	ErrAuth             = errors.New("error authorization")
	ErrPanic            = errors.New("error panic")
)

var (
	ErrUserAlreadyRegistered              = errors.New("user sudah pernah terdaftar")
	ErrUserAlreadyLoggedInInAnotherDevice = errors.New("user masih aktif pada perangkat lain")
	ErrUserAlreadyLoggedInInTheSameDevice = errors.New("user masih aktif di perangkat yang sama")
	ErrUserNeverLoggedIn                  = errors.New("user belum pernah login ke device")
	ErrUserNotLoggedIn                    = errors.New("user belum login ke aplikasi")
	ErrUserOrPasswordNotFound             = errors.New("password salah atau akun tersebut tidak ada")
	ErrKodeOtpNotFound                    = errors.New("kode OTP invalid atau sudah kadaluarsa")
	ErrForceLogoutSessionIdNotFound       = errors.New("user tidak ditemukan atau kode Session ID invalid atau sudah kadaluarsa")
	ErrSendEmailOtp                       = errors.New("email gagal dikirim")
	ErrSendEmailLogoutSession             = errors.New("email gagal dikirim")
	ErrInfoAccountSessionLoggedOutMessage = errors.New("akun anda sedang aktif, silahkan lakukan logout terlebih dahulu")
	ErrMaxLoginAttemptsExceeded           = errors.New("user telah mengganti token, silahkan lakukan login kembali")
)

var (
	ErrNotMatch        = errors.New("new password and confirm password not match")
	ErrPasswordNotSame = errors.New("passwords may not be the same as before")
)
