package constants

// Error Type
const (
	Err                 = "error"
	ErrGeneral          = "error general"
	ErrDataNotFound     = "Data not found"
	ErrDataAlreadyExist = "error data already exist"
	ErrFormatting       = "error formatting"
	ErrDatabase         = "error database"
	ErrAsyncKafka       = "error async kafka"
	ErrTimeout          = "error timeout"
	ErrAuth             = "error authorization"
	ErrPanic            = "error panic"
)

// Error type ErrDatabase
const (
	ErrWhenBeginTx                      = "error when begin transaction"
	ErrWhenExecuteQuery                 = "error when execute query"
	ErrWhenScanResults                  = "error when scan results"
	ErrWhenSelectDB                     = "error when select data from db"
	ErrWhenUpdateDB                     = "error when update data to db"
	ErrWhenDeleteDB                     = "error when delete data from db"
	ErrWhenCommitDB                     = "error when commit db"
	ErrRollBack                         = "error when rollback data from db"
	ErrDuplicateData                    = "error when insert data - dup data"
	ErrAlreadyExistData                 = "error when insert data - already exist"
	ErrWhenCheckingBeforeDeleteDataTkpu = "error when delete data tkpu - already exist"
)

const (
	ErrApplicationSetup                    = "ER5001"
	ErrSessionAndAuthentication            = "ER5002"
	ErrAuthorization                       = "ER5003"
	ErrDatabaseConnection                  = "ER5004"
	ErrHttpConnection                      = "ER5005"
	ErrUndefined                           = "ER9001"
	ErrApplicationSetupDescription         = "error application setup"
	ErrSessionAndAuthenticationDescription = "error session or authentication"
	ErrAuthorizationDescription            = "error authorization"
	ErrDatabaseConnectionDescription       = "error database connection"
	ErrHttpConnectionDescription           = "error http connection"
	ErrUndefinedDescription                = "error undefined"
)

const (
	ErrBadRequest                    = "ER1001"
	ErrUnauthorized                  = "ER1002"
	ErrPaymentRequired               = "ER1003"
	ErrForbidden                     = "ER1004"
	ErrNotFound                      = "ER1005"
	ErrMethodNotAllowed              = "ER1006"
	ErrNotAcceptable                 = "ER1007"
	ErrProxyAuthenticationRequired   = "ER1008"
	ErrRequestTimeout                = "ER1009"
	ErrConflict                      = "ER1010"
	ErrGone                          = "ER1011"
	ErrLengthRequired                = "ER1012"
	ErrPreconditionFailed            = "ER1013"
	ErrPayloadTooLarge               = "ER1014"
	ErrURITooLong                    = "ER1015"
	ErrUnsupportedMediaType          = "ER1016"
	ErrRangeNotSatisfiable           = "ER1017"
	ErrExpectationFailed             = "ER1018"
	ErrImATeapot                     = "ER1019"
	ErrMisdirectedRequest            = "ER1020"
	ErrUnprocessableEntity           = "ER1021"
	ErrLocked                        = "ER1022"
	ErrFailedDependency              = "ER1023"
	ErrTooEarly                      = "ER1024"
	ErrUpgradeRequired               = "ER1025"
	ErrPreconditionRequired          = "ER1026"
	ErrTooManyRequests               = "ER1027"
	ErrRequestHeaderFieldsTooLarge   = "ER1028"
	ErrUnavailableForLegalReasons    = "ER1029"
	ErrInternalServerError           = "ER1030"
	ErrNotImplemented                = "ER1031"
	ErrBadGateway                    = "ER1032"
	ErrServiceUnavailable            = "ER1033"
	ErrGatewayTimeout                = "ER1034"
	ErrHTTPVersionNotSupported       = "ER1035"
	ErrVariantAlsoNegotiates         = "ER1036"
	ErrInsufficientStorage           = "ER1037"
	ErrLoopDetected                  = "ER1038"
	ErrNotExtended                   = "ER1039"
	ErrNetworkAuthenticationRequired = "ER1040"
)

const (
	ErrBadRequestDescription                    = "400 Bad Request"
	ErrUnauthorizedDescription                  = "401 Unauthorized (RFC 7235)"
	ErrPaymentRequiredDescription               = "402 Payment Required"
	ErrForbiddenDescription                     = "403 Forbidden"
	ErrNotFoundDescription                      = "404 Not Found"
	ErrMethodNotAllowedDescription              = "405 Method Not Allowed"
	ErrNotAcceptableDescription                 = "406 Not Acceptable"
	ErrProxyAuthenticationRequiredDescription   = "407 Proxy Authentication Required (RFC 7235)"
	ErrRequestTimeoutDescription                = "408 Request Timeout"
	ErrConflictDescription                      = "409 Conflict"
	ErrGoneDescription                          = "410 Gone"
	ErrLengthRequiredDescription                = "411 Length Required"
	ErrPreconditionFailedDescription            = "412 Precondition Failed (RFC 7232)"
	ErrPayloadTooLargeDescription               = "413 Payload Too Large (RFC 7231)"
	ErrURITooLongDescription                    = "414 URI Too Long (RFC 7231)"
	ErrUnsupportedMediaTypeDescription          = "415 Unsupported Media Type (RFC 7231)"
	ErrRangeNotSatisfiableDescription           = "416 Range Not Satisfiable (RFC 7233)"
	ErrExpectationFailedDescription             = "417 Expectation Failed"
	ErrImATeapotDescription                     = "418 I'm a teapot (RFC 2324, RFC 7168)"
	ErrMisdirectedRequestDescription            = "421 Misdirected Request (RFC 7540)"
	ErrUnprocessableEntityDescription           = "422 Unprocessable Entity (WebDAV; RFC 4918)"
	ErrLockedDescription                        = "423 Locked (WebDAV; RFC 4918)"
	ErrFailedDependencyDescription              = "424 Failed Dependency (WebDAV; RFC 4918)"
	ErrTooEarlyDescription                      = "425 Too Early (RFC 8470)"
	ErrUpgradeRequiredDescription               = "426 Upgrade Required"
	ErrPreconditionRequiredDescription          = "428 Precondition Required (RFC 6585)"
	ErrTooManyRequestsDescription               = "429 Too Many Requests (RFC 6585)"
	ErrRequestHeaderFieldsTooLargeDescription   = "431 Request Header Fields Too Large (RFC 6585)"
	ErrUnavailableForLegalReasonsDescription    = "451 Unavailable For Legal Reasons (RFC 7725)"
	ErrInternalServerErrorDescription           = "500 Internal Server Error"
	ErrNotImplementedDescription                = "501 Not Implemented"
	ErrBadGatewayDescription                    = "502 Bad Gateway"
	ErrServiceUnavailableDescription            = "503 Service Unavailable"
	ErrGatewayTimeoutDescription                = "504 Gateway Timeout"
	ErrHTTPVersionNotSupportedDescription       = "505 HTTP Version Not Supported"
	ErrVariantAlsoNegotiatesDescription         = "506 Variant Also Negotiates (RFC 2295)"
	ErrInsufficientStorageDescription           = "507 Insufficient Storage (WebDAV; RFC 4918)"
	ErrLoopDetectedDescription                  = "508 Loop Detected (WebDAV; RFC 5842)"
	ErrNotExtendedDescription                   = "510 Not Extended (RFC 2774)"
	ErrNetworkAuthenticationRequiredDescription = "511 Network Authentication Required (RFC 6585)"
)

const (
	ErrBadRequestMessage                    = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2001]"
	ErrUnauthorizedMessage                  = "Kendala pada Proses Otorisasi, Silakan coba login kembali [ER2002]"
	ErrPaymentRequiredMessage               = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2003]"
	ErrForbiddenMessage                     = "Kendala pada Proses Otorisasi, Silakan coba login kembali [ER2004]"
	ErrNotFoundMessage                      = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2005]"
	ErrMethodNotAllowedMessage              = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2006]"
	ErrNotAcceptableMessage                 = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2007]"
	ErrProxyAuthenticationRequiredMessage   = "Kendala pada akses, Silakan coba beberapa saat lagi [ER2008]"
	ErrRequestTimeoutMessage                = "Kendala pada akses, Silakan coba beberapa saat lagi [ER2009]"
	ErrConflictMessage                      = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2010]"
	ErrGoneMessage                          = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2011]"
	ErrLengthRequiredMessage                = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2012]"
	ErrPreconditionFailedMessage            = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2013]"
	ErrPayloadTooLargeMessage               = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2014]"
	ErrURITooLongMessage                    = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2015]"
	ErrUnsupportedMediaTypeMessage          = "Tipe File/Media tidak sesuai, Periksa kembali input Anda [ER2016]"
	ErrRangeNotSatisfiableMessage           = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2017]"
	ErrExpectationFailedMessage             = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2018]"
	ErrImATeapotMessage                     = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2019]"
	ErrMisdirectedRequestMessage            = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2020]"
	ErrUnprocessableEntityMessage           = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2021]"
	ErrLockedMessage                        = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2022]"
	ErrFailedDependencyMessage              = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2023]"
	ErrTooEarlyMessage                      = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2024]"
	ErrUpgradeRequiredMessage               = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2025]"
	ErrPreconditionRequiredMessage          = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2026]"
	ErrTooManyRequestsMessage               = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2027]"
	ErrRequestHeaderFieldsTooLargeMessage   = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2028]"
	ErrUnavailableForLegalReasonsMessage    = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2029]"
	ErrInternalServerErrorMessage           = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2030]"
	ErrNotImplementedMessage                = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2031]"
	ErrBadGatewayMessage                    = "Kendala pada akses, Silakan coba beberapa saat lagi [ER2032]"
	ErrServiceUnavailableMessage            = "Kendala pada akses, Silakan coba beberapa saat lagi [ER2033]"
	ErrGatewayTimeoutMessage                = "Kendala pada akses, Silakan coba beberapa saat lagi [ER2034]"
	ErrHTTPVersionNotSupportedMessage       = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2035]"
	ErrVariantAlsoNegotiatesMessage         = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2036]"
	ErrInsufficientStorageMessage           = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2037]"
	ErrLoopDetectedMessage                  = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2038]"
	ErrNotExtendedMessage                   = "Kendala pada Server Aplikasi, Silakan hubungi administrator [ER2039]"
	ErrNetworkAuthenticationRequiredMessage = "Kendala pada akses, Silakan coba beberapa saat lagi [ER2040]"
)

const (
	InfoDataJabatanNotFound = "Data jabatan tidak ditemukan pada user terkait"
)

const (
	InfoDataPrivilegeNotFound     = "Data privilege tidak ditemukan pada user terkait"
	InfoDataListPrivilegeNotFound = "Data privilege tidak ditemukan"
)

const (
	InfoDataAplikasiNotFound = "Data aplikasi tidak ditemukan pada user terkait"
)

// Error grpc
const (
	ErrGrpc            = "error grpc"
	ErrGrpcUnavailable = "service '%s' is unavailable"
)
